### ISSUE TITLE
test login.xml

### ISSUE THREAD

**Issue by Tobiasvanc** [wollf92/ToGather2#3]
Cant find a way to "run' it myself... can you try?

**Comment by markkuhar** [comment]
pulled your commit and it runs just fine on phone and in emulator aswell

**Comment by Tobiasvanc** [comment]
also the new login.xml? Haven't linked it to the actual stuff, would need to open that page and verify it can login using email1 p1

**Comment by markkuhar** [comment]
No without login.xml. Login page is loaded from activity_login.xml as from the start, but current login design (activity_login.xml) looks good for to me i dont think it needs changing

But if you want to link login.xml to login activity you need change https://github.com/wollf92/ToGather2/blob/3a7a6420c6a5347c43a70daea32122d71852db96/app/src/main/java/com/example/wollf/togather/LoginActivity.java#L64 
to `setContentView(R.layout.login);`
